### ISSUE TITLE
Looting

### ISSUE THREAD

**Issue by knutgen** [Optimat/Optimat.EO#1]
The bot works good. however it said in your guide that it supports all missions marked green in the automisson tab, but the bot won't loot any mission items. instead it just abandons the loot and starts looking for the loot in other wrecks/containers. is there any way to add the loot function?

**Comment by Viir** [comment]
Copied from https://github.com/botengine-de/Optimat.EO/issues/1

> but the bot won't loot any mission items. instead it just abandons the loot and starts looking for the loot in other wrecks/containers.

This can happen if the bot cannot recognize the items displayed in the selected containers view in the inventory.
I recommend you set the inventory windows view of the selected container to "list" as other view types are not supported.
